### ISSUE TITLE
SMPL / Instances frame index mismatch

### ISSUE THREAD

**Issue by DavideA** [ziyc/drivestudio#36]
Hi all,

I am trying to fit omnire on nuScenes, and for some scenes I am facing the following exception while loading `smpl.pkl` files:

```
Loading SMPL:  69%|██████▉   | 135/196 [00:00<00:00, 1342.00it/s]                                                                                                                                                Traceback (most recent call last):                                                                                                                                                                                 File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/tools/train.py", line 377, in <module>                                                                  final_step = main(args)                                                                                                                                                                                        File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/tools/train.py", line 111, in main                                                                      dataset = DrivingDataset(data_cfg=cfg.data)                                                                                                                                                                    File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/datasets/driving_dataset.py", line 78, in __init__                                                      self.pixel_source, self.lidar_source = self.build_data_source()
  File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/datasets/driving_dataset.py", line 148, in build_data_source
    pixel_source = import_str(self.data_cfg.pixel_source.type)(
  File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/datasets/nuscenes/nuscenes_sourceloader.py", line 168, in __init__
    self.load_data()
  File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/datasets/base/pixel_source.py", line 726, in load_data
    self.load_objects()
  File "/prj/corp/airesearch/lasvegas/vol1-scratch/users/dabati/projects/arriver-gda/third_party/drivestudio/datasets/nuscenes/nuscenes_sourceloader.py", line 321, in load_objects
    ii = instances_info[str(instance_id)]['frame_annotations']["frame_idx"].index(fi)
ValueError: 135 is not in list
```

To my understanding, the smpl file refers to a frame index that is not present in the `instances_info.json` file. Any ideas?

**Comment by SophieZhou** [comment]
where is the smpl.pkl model? I have not found it.
